[sheets]
title = "FieldFlow"

[google_oauth]
client_id = ""
client_secret = ""
redirect_uri = "http://localhost:8501"

[gcp_service_account]
type = "service_account"
project_id = ""
private_key_id = ""
private_key = "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
client_email = ""
token_uri = "https://oauth2.googleapis.com/token"

[microsoft_oauth]
client_id = ""
